[project]
name = "applied-data-science-ri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PlanellesAlex", email = "alex.planelles.a@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
]

[project.scripts]
applied-data-science-ri = "applied_data_science_ri:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
